extends: standard
installedESLint: true
plugins:
  - standard
  - promise
env:
  node: true
  mocha: true
globals:
  Vue: true
  axios: true
  _: true
rules:
  no-multi-spaces: ["error", { exceptions: { "Property": true, "VariableDeclarator": true } }]
