extends: standard
installedESLint: true
plugins:
  - standard
  - promise
env:
  node: true
  mocha: true
globals:
  Vue: true
  axios: true
  _: true
  # test library
  monky: true
  expect: true
  dbCleaner: true
rules:
  no-multi-spaces: ["error", { exceptions: { "Property": true, "VariableDeclarator": true } }]
